### ISSUE TITLE
snippets.sh: Add snippets for ping and pong

### ISSUE THREAD

**Issue by RaduNichita** [multiversx/mx-ping-pong-sc#8]
Hi.

I just bumped into the repo when I tried running some tutorials and have a bit of trouble using ping and pong from the command line. I didn't find a command for ping and pong the smart contract with `erdpy` in `interaction/snippets.sh`. Could you add some examples for that, please?

I think there would also be very useful fur other newbies trying out thing blockchain.

**Comment by CostinCarabas** [comment]
Solved in https://github.com/multiversx/mx-ping-pong-sc/pull/10.
Thanks!
