### ISSUE TITLE
Rename elrond.json to multiversx.json, erdpy.json to mxpy.json

### ISSUE THREAD

**Issue by bluedragon1120** [multiversx/mx-ping-pong-sc#9]
Hi,

I tried to deploy smart contract on devnet with "mxpy contract deploy" but it wasn't worked properly.
I renamed elrond.json to multiversx.json, erdpy.json to mxpy.json in ping-pong directory and tried to deploy again.
Finally, I deployed smart contract successfully.

All the best!!!
Thanks

**Comment by CostinCarabas** [comment]
Issue is fixing in PR https://github.com/multiversx/mx-ping-pong-sc/pull/10.
Thank you for reporting!

**Comment by CostinCarabas** [comment]
Fixed, closing this issue.
Thanks for your contribution!
